id: opecha:P008014
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25392
  title: རི་མོར་བལྟས་ནས་འཚོ་བའི་བརྡ་རྟགས་ངོས་འཛིན་པ།
  volume:
    2219c9fd8f874a1297e5df1d7027406f:
      image_group_id: I1KG25394
      title: Volume 1 of ri mor bltas nas 'tsho ba'i brda rtags ngos 'dzin pa/
      volume_number: 1
      total_pages: 66
  author: ''
ebook_metadata:
  title: རི་མོར་བལྟས་ནས་འཚོ་བའི་བརྡ་རྟགས་ངོས་འཛིན་པ།
  author: ''
  sku: P008014
  cover: cover.jpg
  layers:
  - pagination
