id: P008014
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25392
  title: རི་མོར་བལྟས་ནས་འཚོ་བའི་བརྡ་རྟགས་ངོས་འཛིན་པ།
  author: ''
  volumes:
    a26734badec5401298c5c93633bb3c38:
      image_group_id: I1KG25394
      title: ''
      volume_number: 1
      total_pages: 66
ebook_metadata:
  title: རི་མོར་བལྟས་ནས་འཚོ་བའི་བརྡ་རྟགས་ངོས་འཛིན་པ།
  author: ''
  sku: P008014
  cover: cover.jpg
  layers:
  - pagination
